### PR TITLE
Run Single Model on Multiple GPUs

### PR DESCRIPTION
**Pull request by mpskex**
You might have many small GPUs, which may not load RWKV. But we can parallelize it!
- Easy to use, just tell your program how many GPUs you want to use.
- Compatible with `CUDA_VISIBLE_DEVICES` environment variable
  -  which means you can assign any devices you desire
- For single GPU instance, just set `args.NUM_PARA_GPUS=1`

### CODE REVIEW

**Comment by BlinkDL** [comment]
Great work :) My idea is to keep the main ChatRWKV repository simple (easy for everyone to learn its code), while having some community forks with cutting-edge functions.

If you are interested, I can tell everyone to add new functions to your fork.

**Comment by mpskex** [comment]
That would be great! I am also working on other features... just don't know where to contribute. It would be awesome if you could show me where and how!

**Comment by mpskex** [comment]
Nothing offensive, but honestly I found the `global` variables are abused in the current code base. It may be a challenge for new comers to read and understand the work.

**Comment by BlinkDL** [comment]
> Nothing offensive, but honestly I found the `global` variables are abused in the current code base. It may be a challenge for new comers to read and understand the work.

Yeah my code is full of bad designs :) needs some refactor one day...

**Comment by BlinkDL** [comment]
Now ChatRWKV v2 supports this too :)

**Comment by mpskex** [comment]
That's cool! I think I will close this PR now~

**Pull request closed without merging**
